### PR TITLE
Added Events, minor bug fixes, and Readme updates

### PR DESCRIPTION
**Pull request by fredvisser**
Also, confirmed that the lvdist still builds successfully

### CODE REVIEW

**Comment by fredvisser** [comment]
@rajsite - I've added the Event Structure to this PR. Let me know if you see any issues.

**Comment by cglzaguilar** [comment]
Fred please rebase your changes from master. We have new versions now.

**Comment by fredvisser** [comment]
Rebased my changes to master, and updated the lvprojectcache file to correctly open the Main.gviweb front panel on project open.

**Comment by fredvisser** [comment]
Closing and recreating in an attempt to resolve strange merge conflict.

**Pull request closed without merging**
