### PR TITLE
JSLI Examples

### PR DESCRIPTION
**Pull request by doczhivago**
Created new branch to avoid merge conflicts. Examples updated with comments from WebVI team and G Content Review team.

### CODE REVIEW

**Comment by rajsite** [comment]
For the two JSLI examples listed in the top-level README can we add a notice on the first line of the description stating something like:

```
**Note: JSLI examples can only be used with the NXG 3 Beta. To access the NXG 3 Beta visit [ni.com/techpreview](https://ni.com/techpreview)**
```

**Comment by mehagar** [comment]
One more thing, Frank. I think you need to delete the Builds folder as well from both examples.

**Comment by rajsite** [comment]
The Build folders should be checked into GitHub, not perforce

**Comment by rajsite** [comment]
I'll just go ahead and merge it and then update the README

**Comment by doczhivago** [comment]
Great, thanks for updating the readme. I will also delete the jsli-examples branch.

**Pull request merged**
